<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>gazebo_nav_bringup</name>
  <version>1.0.0</version>
  <description>Launch files and configs for Gazebo SLAM and Nav2 autonomous navigation with Turtlebot3</description>
  <maintainer email="saman.aboutorab@gmail.com">saman-aboutorab</maintainer>
  <license>MIT</license>

  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
  <exec_depend>py_trees_ros</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
